[bar]
background = "#1a1a1a"
background-alpha = 0.93
text = "#dddddd"
active = "#00ff99"
size-horizontal = 34

[popups]
background = "#2a2a2a"
background-alpha = 0.96
text = "#dddddd"
border = "#555555"
border-alpha = 1.0

[tooltip]
background = "#2a2a2a"
background-alpha = 0.96
text = "#dddddd"
border = "#555555"
border-alpha = 1.0

[font]
family = "JetBrainsMono Nerd Font"
base-size = 12
