
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "rofi -show drun"
local browser     = "flatpak run app.zen_browser.zen"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("GTK_THEME", "Breeze-Dark")
hl.env("QT_QPA_PLATFORMTHEME", "kde")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(00000000)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 2.5, bezier = "easeOutQuint", style = "slidefadevert -50%" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

hl.workspace_rule({
    workspace = "special:scratchpad",
    on_created_empty = "hypr-dropdown-start",
    gaps_out = { top = 0, left = 20, right = 20, bottom = 540 },
})

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = true, -- hyprpaper manages the desktop background
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "dvorak",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            tap_and_drag = true,
            drag_lock = 1,
            clickfinger_behavior = true,
            disable_while_typing = true,
            middle_button_emulation = false,
            scroll_factor = 1.0,
        },
    },
})

hl.gesture({
    fingers = 4,
    direction = "horizontal",
    action = "workspace"
})

hl.gesture({
    fingers = 3,
    direction = "swipe",
    action = "move"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

local function bind(keys, description, dispatcher, options)
    options = options or {}
    options.description = description
    return hl.bind(keys, dispatcher, options)
end

-- Omarchy-style application bindings
bind(mainMod .. " + SPACE", "Applications", hl.dsp.exec_cmd(menu))
bind(mainMod .. " + R", "Applications", hl.dsp.exec_cmd(menu))
bind(mainMod .. " + K", "Keybinding help", hl.dsp.exec_cmd("hypr-keybindings"))
bind(mainMod .. " + ESCAPE", "System menu", hl.dsp.exec_cmd("hypr-system-menu"))
bind(mainMod .. " + M", "Log out", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.exit()'"))
bind(mainMod .. " + CTRL + L", "Lock system", hl.dsp.exec_cmd("pgrep -x hyprlock >/dev/null || hyprlock"))
bind(mainMod .. " + RETURN", "Terminal", hl.dsp.exec_cmd(terminal))
bind(mainMod .. " + SHIFT + RETURN", "Browser", hl.dsp.exec_cmd(browser))
bind(mainMod .. " + SHIFT + F", "File manager", hl.dsp.exec_cmd(fileManager))
bind(mainMod .. " + SHIFT + N", "Editor", hl.dsp.exec_cmd(terminal .. " -e vim"))
bind(mainMod .. " + SHIFT + ALT + M", "CLIamp", hl.dsp.exec_cmd(terminal .. " --class cliamp -e cliamp"))
bind(mainMod .. " + CTRL + T", "Activity", hl.dsp.exec_cmd(terminal .. " --class activity --override initial_window_width=1100 --override initial_window_height=700 -e btop"))

-- Omarchy-style window navigation and tiling
bind(mainMod .. " + W", "Close window", hl.dsp.window.close())
bind(mainMod .. " + Q", "Close window", hl.dsp.window.close())
bind(mainMod .. " + T", "Toggle floating", hl.dsp.window.float({ action = "toggle" }))
bind(mainMod .. " + L", "Toggle scrolling layout", hl.dsp.exec_cmd("hypr-workspace-layout-toggle"))
bind(mainMod .. " + J", "Toggle split", hl.dsp.layout("togglesplit"))
bind(mainMod .. " + P", "Pseudo window", hl.dsp.window.pseudo())
bind(mainMod .. " + F", "Fullscreen", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
bind(mainMod .. " + CTRL + F", "Tiled fullscreen", hl.dsp.exec_cmd("hypr-window-tiled-fullscreen-toggle"))
bind(mainMod .. " + ALT + F", "Maximize", hl.dsp.window.fullscreen({ mode = "maximized" }))
bind(mainMod .. " + O", "Pop window out", hl.dsp.exec_cmd("hypr-window-pop"))

for _, direction in ipairs({ "left", "right", "up", "down" }) do
    bind(mainMod .. " + " .. direction, "Focus " .. direction, hl.dsp.focus({ direction = direction }))
    bind(mainMod .. " + SHIFT + " .. direction, "Swap window " .. direction, hl.dsp.window.swap({ direction = direction }))
    bind(mainMod .. " + ALT + " .. direction, "Group window " .. direction, hl.dsp.window.move({ into_group = direction }))
end

bind("ALT + TAB", "Next window", hl.dsp.window.cycle_next())
bind("ALT + SHIFT + TAB", "Previous window", hl.dsp.window.cycle_next({ next = false }))
bind("CTRL + ALT + TAB", "Next monitor", hl.dsp.focus({ monitor = "+1" }))
bind("CTRL + ALT + SHIFT + TAB", "Previous monitor", hl.dsp.focus({ monitor = "-1" }))

for workspace = 1, 10 do
    local key = "code:" .. tostring(workspace + 9)
    bind(mainMod .. " + " .. key, "Workspace " .. workspace, hl.dsp.focus({ workspace = workspace }))
    bind(mainMod .. " + SHIFT + " .. key, "Move to workspace " .. workspace, hl.dsp.window.move({ workspace = workspace }))
    bind(mainMod .. " + SHIFT + ALT + " .. key, "Move silently to workspace " .. workspace, hl.dsp.window.move({ workspace = workspace, follow = false }))
end

bind(mainMod .. " + TAB", "Next workspace", hl.dsp.focus({ workspace = "e+1" }))
bind(mainMod .. " + SHIFT + TAB", "Previous workspace", hl.dsp.focus({ workspace = "e-1" }))
bind(mainMod .. " + CTRL + TAB", "Former workspace", hl.dsp.focus({ workspace = "previous" }))

bind(mainMod .. " + S", "Toggle scratchpad", hl.dsp.workspace.toggle_special("scratchpad"))
bind(mainMod .. " + grave", "Toggle scratchpad", hl.dsp.workspace.toggle_special("scratchpad"))
bind(mainMod .. " + ALT + S", "Move to scratchpad", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }))
bind(mainMod .. " + SHIFT + grave", "Move to scratchpad", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }))

bind(mainMod .. " + G", "Toggle window group", hl.dsp.group.toggle())
bind(mainMod .. " + ALT + G", "Remove window from group", hl.dsp.window.move({ out_of_group = true }))
bind(mainMod .. " + ALT + TAB", "Next grouped window", hl.dsp.group.next())
bind(mainMod .. " + ALT + SHIFT + TAB", "Previous grouped window", hl.dsp.group.prev())

bind(mainMod .. " + code:20", "Expand window left", hl.dsp.window.resize({ x = -100, y = 0, relative = true }))
bind(mainMod .. " + code:21", "Shrink window left", hl.dsp.window.resize({ x = 100, y = 0, relative = true }))
bind(mainMod .. " + SHIFT + code:20", "Shrink window up", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))
bind(mainMod .. " + SHIFT + code:21", "Expand window down", hl.dsp.window.resize({ x = 0, y = 100, relative = true }))

bind(mainMod .. " + mouse_down", "Next workspace", hl.dsp.focus({ workspace = "e+1" }))
bind(mainMod .. " + mouse_up", "Previous workspace", hl.dsp.focus({ workspace = "e-1" }))
bind(mainMod .. " + mouse:272", "Move window", hl.dsp.window.drag(), { mouse = true })
bind(mainMod .. " + mouse:273", "Resize window", hl.dsp.window.resize(), { mouse = true })

bind(mainMod .. " + SHIFT + SPACE", "Toggle top bar", hl.dsp.exec_cmd("qs ipc call bar toggle"))
bind(mainMod .. " + comma", "Dismiss notification", hl.dsp.exec_cmd("makoctl dismiss"))
bind(mainMod .. " + SHIFT + comma", "Dismiss all notifications", hl.dsp.exec_cmd("makoctl dismiss --all"))
bind(mainMod .. " + ALT + comma", "Invoke notification action", hl.dsp.exec_cmd("makoctl invoke"))
bind("PRINT", "Screenshot screen", hl.dsp.exec_cmd("hypr-screenshot screen"))
bind("SHIFT + PRINT", "Screenshot region", hl.dsp.exec_cmd("hypr-screenshot region"))
bind(mainMod .. " + PRINT", "Screenshot window", hl.dsp.exec_cmd("hypr-screenshot window"))

-- Laptop multimedia keys for volume and LCD brightness
bind("XF86AudioRaiseVolume", "Volume up", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
bind("XF86AudioLowerVolume", "Volume down", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
bind("ALT + XF86AudioRaiseVolume", "Volume up precise", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+"), { locked = true, repeating = true })
bind("ALT + XF86AudioLowerVolume", "Volume down precise", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"), { locked = true, repeating = true })
bind("XF86AudioMute", "Mute audio", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
bind("SHIFT + XF86AudioMute", "Select audio output", hl.dsp.exec_cmd("hypr-audio-output-select"), { locked = true })
bind("XF86AudioMicMute", "Mute microphone", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

bind("XF86MonBrightnessUp", "Brightness up", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
bind("XF86MonBrightnessDown", "Brightness down", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
bind("ALT + XF86MonBrightnessUp", "Brightness up precise", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%+"), { locked = true, repeating = true })
bind("ALT + XF86MonBrightnessDown", "Brightness down precise", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%-"), { locked = true, repeating = true })
bind("SHIFT + XF86MonBrightnessUp", "Brightness maximum", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 100%"), { locked = true })
bind("SHIFT + XF86MonBrightnessDown", "Brightness minimum", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%"), { locked = true })

bind("XF86AudioNext", "Next track", hl.dsp.exec_cmd("playerctl next"), { locked = true })
bind("ALT + XF86AudioPlay", "Next track", hl.dsp.exec_cmd("playerctl next"), { locked = true })
bind("XF86AudioPause", "Play or pause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
bind("XF86AudioPlay", "Play or pause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
bind("XF86AudioPrev", "Previous track", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
bind("ALT + SHIFT + XF86AudioPlay", "Previous track", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

bind(mainMod .. " + CTRL + Z", "Zoom in", function()
    local zoom = hl.get_config("cursor.zoom_factor") or 1
    hl.config({ cursor = { zoom_factor = zoom + 1 } })
end)

bind(mainMod .. " + CTRL + ALT + Z", "Reset zoom", function()
    hl.config({ cursor = { zoom_factor = 1 } })
end)


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    name  = "float-activity",
    match = { class = "^activity$" },
    float = true,
})

hl.window_rule({
    name  = "float-okular",
    match = { class = "^org[.]kde[.]okular$" },
    float = true,
    size  = "1100 700",
})

local exec_onces = {
    "/usr/libexec/pam_kwallet_init",
    "hypr-network-audio-safe --watch 15",
    "hyprpaper",
    "qs --no-duplicate",
    "mako",
}

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP GTK_THEME QT_QPA_PLATFORMTHEME")
    hl.exec_cmd("/usr/libexec/hyprpolkitagent")

    for _, cmd in ipairs(exec_onces) do
        hl.exec_cmd(cmd)
    end
end)
